#  Print the following text in the terminal: "Hello world"

# INFO IMPORTANTE: UNICAMENTE VAMOS A UTILIZAR PRINT PARA IMPRIMIR EL RESULTADO ESPERADO DEL EJERCICIO. NO VAMOS A IMPRIMIR NI TEXTO QUE INTRODUZCA AL PROYECTO, NI TEXTO ANTES DE SOLICITAR DATOS AL USUARIO.



